<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="TermsofService.aspx.cs" Inherits="Welleazy.TermsofService" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <link href="images/welleazy-logo.png" rel="icon" />
     <!-- Bootstrap CSS CDN -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <%--<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">--%>

        <!-- Our Custom CSS -->
        <link href="../css/style4.css" rel="stylesheet" />
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <title> Welleazy | Terms of Service and Policies</title>
</head>
<body>
    
	  <nav class="navbar navbar-expand-lg bg-white mb-3">
          <div class="container">
    <a class="navbar-brand" href="#"><img src="/images/image-logo-welnext.png" alt=""></a>
    

    
  </div>
      </nav>
    <form id="form1" runat="server">
        <div class="form-group" style="height:auto; background-color: white; padding:40px;">
        <h2 style="">Policies & Terms of use</h2>
            <span style="">
                <img src="/images/Terms_Services.jpg" alt="" />
            </span> 
                                   
                     <br />
            <div class="form-group" style="margin-top:-40px;">

           
            <h3 style="color:#0869b1;"><b>General Terms And Conditions Of Service</b></h3>
                <div style="border-radius:15px; border:2px solid #bbbaba; overflow-y:auto; height:600px;">
                    <span style="padding: 20px; font-size: 15px; color: #2f2e2e;">
                        This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures. By clicking on the “I ACCEPT” or “Agreed”  button, You are consenting to be bound by these General Terms and Conditions for using Website/App and for availing the services of Welleazy. Please ensure that You read these terms and conditions carefullybefore You use the service of this portal. If You do not agree to be bound by (or cannot comply with) any or all of them, do not check/click the “IACCEPT” or “AGREE” box, do not complete the registration process, and do not attempt to access or use any services of Welleazy including its Website/App .When You register/access any services of Welleazy, You are bound by all of the terms and conditions which are intended to be fully effective and binding including privacy policy and all other operating rules, policies, and procedures that may be published/updated on the Website.
                        <br /><br />

These general terms and conditions is an agreement made between M/s. Welleazy Healthtech Solutions Private Limited, India (hereinafter referred to as “Welleazy” or “Company”) and the user (hereinafter referred to as “You” or “Your” or “User”) who avails any service from Welleazy. The word You shall mean the individual, company or any other legal entity for which the terms and conditions of this agreement are agreed to and includes affiliates of the Company or any other legal entity. If You agree to these terms and conditions of a company or any other legal entity, You represent that You have the authority to bind such entity and its affiliates. You represent that You are a valid person meeting age and other requirements for entering into an agreement and in the event that You are a parent or guardian of a minor, You represent and warrant that You have the legal capacity to act on behalf of such minor and acknowledge and agree that the provisions of this agreement will be equally applicable to the minor.
<br /><br />
The Url: <asp:HyperLink ID="HyperLink1" runat="server" ForeColor="#0033cc" NavigateUrl="https://www.welleazy.com/">www.welleazy.com</asp:HyperLink> (“Website/Site”) and its mobile application (“App”) is owned by the legal entity ‘Welleazy Healthtech Solutions Private Limited’. The terms and conditions of engagement with Welleazy as per these general terms and conditions of service will apply in all cases where You register / avail services from Welleazy and even if You are a guest and not a registered user of the Website/App. This agreement supersedes all previous oral and written terms and conditions (if any) communicated to You relating to Your use of the Website/App to avail the services.<br /><br />

<span runat="server" style="color:#0869b1; font-size:x-large;"><b>Change to the Terms of Use:</b></span><br /><br />
Welleazy reserves the right that at its sole discretionit may change, modify, add or remove these terms and conditions at any time in part or in whole without prior notice to You and such modifications shall be effective immediately upon posting the revised terms and conditions. You agree to check and review these terms and conditions periodically to be aware of such changes/modifications and Your continued use of Welleazy Website/App following the posting of revised Terms and Conditions of Use means that You accept and agree to the changes and the revised Terms of Use. We do not undertake to notify You of proposed or actual changes. In addition, when using certain services through the Website, You may be subject to any additional terms and conditions by Welleazy applicable to such services and therefore Your use of such services shall be subject to the additional terms and conditions that may be posted on the Services from time to time, including, without limitation, the Privacy Policy and other policies. All such terms are hereby incorporated by reference into these Terms of Service.<br /><br />

<span runat="server" style="color:#0869b1; font-size:x-large;"><b>Access and Use of Services:</b></span><br /><br />
<b>Service Description:</b><br /><br />

Welleazy through its partner organisations primarily provides primary healthcare services and related services and does not treat medical emergencies.
You understand and agree that use of Welleazy services is entirely at Your own risk and that in no event shall Welleazy be liable for any direct, indirect, incidental, consequential, special, exemplary, punitive, or any other monetary or other damages, fees, fines, penalties, or liabilities arising out of or relating in any way to this Site, or sites accessed through this Site, App, and / or content or information provided herein (hereinafter referred to as ‘general indemnity’ protection to Welleazy). Information provided on Welleazy Website/App should not be construed as medical advice or used for treatment purposes and no content in the Website / App intends to provide medical advice, professional diagnosis, opinion, treatment to You or any other individual.
<br /><br />
<b>Third Party Links/Materials:</b><br /><br />

Under no circumstances will Welleazy be liable in any way for any content/information or materials of any third parties contained in the services delivered by Welleazy via this Website / App, which  may include hypertext links or pointers to information that is created, owned and managed by external medical service providers (hereinafter called ‘MSPS’) to assist You in Your services or any promotional links. When You select a link to an outside website/services/resources, You agree that You do so at Your risk and are subject to the terms and conditions of the owners / sponsors of that outside website. Welleazy does not guarantee the availability of such linked pages at all times. The inclusion of any link does not imply affiliation, endorsement or adoption by us of the linked site. Welleazy has no control over such websites, services and resources and Welleazy is not responsible for and does not endorse such sites, services and resources. You agree to receive reports, documents, notifications, confirmations, administrative messages, communications, phone calls and messages from Welleazy or the owners / sponsors of external websites notwithstanding a DND (do not disturb) registration You may have with the providers of communication channels.
<br /><br />
You agree and grant Your consent that Welleazy may record all conversations, audio or video calls for purposes of medical records and quality and training purposes.
<br /><br />
<b>Medical Service Providers:</b><br /><br />
Services offered by the company are not health insurance policies. Welleazy provides the services through own or independent medical professionals/ organizations/ institutions/ ambulance providers/ pathology labs/ radiology labs/ others (“Medical Service Providers”). Welleazy may provide users with discounted services either through self or through any of the Medical Service Providers at certain locations and access to including, but not limited to, virtual health services.
<br /><br />
The Medical Service Providers are independent entities/professionals in private practice and are neither employees nor agents of Welleazy and/or its parents, subsidiaries or affiliates. Welleazyis only an aggregator/ facilitator of independent Medical Service Providers and merely an intermediary providing the Website and App as a platform to offer services to You/Users. Welleazy does not recommend or suggest any particular Medical Service Provider or promote any particular Medical Service Provider’s name or practice. Further, Welleazy does not make any representations or warranties with respect to Medical Service Providers or the quality of the healthcare services they he/she may provide. Welleazy shall not be responsible for any breach of service or service deficiency by any Medical Service Provider.
<br /><br />
Welleazy makes no express or implied representations or warranties about the description, quality, fitness for any particular purpose, productiveness, or any other matter in relation to any product or service and disclaims any implied warranties, including, but not limited to, warranties or implied warranties of merchantability or fitness for a particular purpose or use or non-infringement. In addition to this Welleazy also does not authorize anyone to make any warranty on Welleazy’s behalf.
<br /><br />
You shall not deliberately use the Services in any way that is unlawful or harms Welleazy or Medical Service Providers, Welleazy’s directors, employees, affiliates, distributors, partners, service providers and/or other users of the Website. If Welleazy suspects any illegal, wrongful or fraudulent activity, then notwithstanding any other rights that Welleazy may have. Welleazy reserves the right to inform the relevant government or law enforcement authorities. Welleazy will cooperate in all investigative procedures or requests for access / information initiated by any such government or law enforcement authorities.
<br /><br />
Welleazy reserves the right, in its sole discretion and without any obligation, to make improvements to, or correct any error or omissions in, any component of, or term relating to, the Services provided to You by Welleazy and update information from time to time.
<br /><br />
Any advice provided by any Medical Service Provider shall depend solely on the completeness and accuracy of the information provided by You. Neither Welleazy nor any Medical Service Provider shall be responsible for any damage, whether physical, emotional, psychological or financial, caused to You due to any improper/unintended use of the Services, which includes but is not limited to the misinterpretation of the advice given by any Medical Service Provider to you.
<br /><br />
The Service offered by Company and Medical Service Provider are provided on “As Is” and “As Available” basis and may be subject to certain limitations. Consequently, in no event shall Welleazy and/or any Medical Service Provider be liable to You or any third party for any indirect, consequential, exemplary, incidental, special, or punitive damages, including lost business/revenue/profit/goodwill or damages arising from Your use or unavailability of the Services and/or any other the services offered to You by Welleazy in any manner whether or not Welleazy has been warned of the possibility of such damages or could have reasonably foreseen such damages. You shall not be entitled to specific performance of any of the Terms. The foregoing limitation of liability shall apply to the fullest extent permitted by law in the applicable jurisdiction and, regardless of the form of the action, will at all times be limited to the aggregate of amount received from You by Welleazy. You specifically agree and understand that neither Welleazy nor any Medical Service Provider is liable to You for any content or illegal conduct of any third party and that You alone accept such risk of harm.
<br /><br />
The views and suggestions expressed by Medical Service Providers in the course of providing the Services shall in no manner be construed as an endorsement by Welleazy. Welleazy shall not be responsible in any manner whatsoever for any act, omission, treatment, diagnosis, advice, view, suggestion or opinion, whether medical or non-medical, professional or non-professional conduct of any Medical Service Provider for any reason whatsoever. Welleazy is free to change the Medical Service Providers at its sole discretion. Welleazy is entitled, without any liability whatsoever, to refuse, limit, suspend, vary or discontinue the provision of any of the Services at any time for any reasonable cause as Welleazy may deem fit.
<br /><br />
Notwithstanding the aforesaid, the provision of services by any Medical Service Provider and any matter relating thereto including but not limited to the manner and the form in which the services may be made available to You by any Medical Service Provider may be altered, withdrawn, modified or changed at any point of time. You agree to be bound by any such modifications.
<br /><br />
<b>Representations and Warranties</b><br /><br />

You hereby represent and warrant that:<br />
                        <ul style="list-style: decimal;">
                            <li>You are eligible for registration on the Website/App and creation of an Account in terms of these Terms and Conditions and have all requisite power and authority to perform the obligations imposed herein.
                            </li>
                            <li>
                                You are 18 years of age or older and that Your use of the Services shall not violate any applicable law or regulation or any existing agreement, any order or judicial pronouncement to which You are a party.
                                <br />
                                In case a minor person (i.e. individual less than 18 years of age) obtains Services, then You will ensure that the minor person observes and complies with all the terms and conditions and assume full liability for any non-compliance or violation of the terms by the minor in a way that any non-compliance or violation by the minor person shall be deemed to have been committed by you. All information You submit is complete and accurate, current and updated and that You agree to maintain the completeness and accuracy of such information.
                                <br />
                                You will use the services solely for Your personal and non-commercial use; and You will not use the services in any way that is unlawful, or harms any person or entity.
                            </li>
                            <li>
                                You shall not use the Website/App/Services in a way that infringes or misappropriates a third party’s intellectual property rights or personal rights;
                            </li>
                        </ul>


<b>User Covenants</b><br /><br />

Welleazy/Company hereby informs the User that the User is not permitted to host, display, upload, modify, publish, transmit, update or share any information that:
<br />
                        <ul style="list-style:decimal;">
                            <li>
                                belongs to another person and to which the User does not have any right to;
                            </li>
                            <li>
                                is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, paedophilic, libellous, invasive of another’s privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever;
                            </li>
                            
                            <li>
                                harm minors in any way;
                            </li>
                            <li>
                                infringes any patent, trademark, copyright or other proprietary rights;
                            </li>
                            <li>
                                violates any law for the time being in force;
                            </li>
                            <li>
deceives or misleads the addressee (or end­user or User) about the origin of such messages or communicates any information which is grossly offensive or menacing in nature;
                            </li>
                            <li>
                                impersonate another person;
                            </li>
                            <li>
                                contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource;
                            </li>
                            <li>
                                threatens the unity, integrity, defence, security or sovereignty of india, friendly relations with foreign states, or public order or causes incitement to the commission of any cognisable offence or prevents investigation of any offence or is insulting any other nation.
                            </li>
                           
                        </ul>
<b>Prohibited Use:</b><br /><br />

Without limiting the foregoing, You/User agree to not use the Services on:<br />
<ul style="list-style:decimal;">
    <li>
        violating or attempting to violate the integrity or security of the services or any software of Welleazy;
    </li>
    <li>
        transmitting any information (including job posts, messages and hyperlinks) on or through the services that is disruptive or competitive to the provision of Services by Welleazy;
    </li>
    <li>
        intentionally submitting on the services any incomplete, false or inaccurate information;
    </li>
    <li>
        making any unsolicited communications to other users;
    </li>
    <li>
        using any engine, software, tool, agent or other device or mechanism (such as spiders, robots, avatars or intelligent agents) to navigate or search the service;
    </li>
    <li>
        attempting to decipher, decompile, disassemble or reverse engineer any part of the services unless explicitly permitted by Welleazy;
    </li>
    <li>
        copying or duplicating in any manner any of the Welleazy content or other information available from the service;
    </li>
    <li>
        framing or hotlinking or deeplinking any Welleazy content.
    </li>
    <li>
        circumventing or disabling any digital rights management, usage rules, or other security features of the software.
    </li>
    <li>
        interfering with or disrupting the Services or servers or networks connected to the Services, or disobey any requirements, procedures, policies or regulations of networks connected to the Services; or
    </li>
    <li>
        harvesting or collecting email addresses and/or identifiable information of other users from the Services by electronic or other means
    </li>
    <li>
        any other activity which is considered undesirable or illegal under law
    </li>
</ul>
<b>Infringements:</b><br /><br />

Any infringements of Patents, Intellectual Property Rights, Trademarksif noticed shall be brought to the notice of Welleazy by writing to hello@welleazy.com. Welleazy retains to right to modify or remove any infringed contents / offerings in order to void the infringement without any admission to the liability or any other defenses, rights or remedies available to Welleazy.
<br /><br />
<b>Proprietary Rights and Content Ownership:</b>
<br /><br />
The Website, App and Confidential Information, including but not limited to all intellectual property rights such as company name, logos, product and service names, trademarks, services marks etc. shall remain the property of Welleazy. Welleazy has all ownership rights for the design, contents and packaging of its services and offerings. Any unauthorized use or copying or display or distribution or exploitation of the design or terms and contents of the services and offerings are prohibited.
<br /><br />
<b>Notices:</b><br /><br />

All notices and other communications required or permitted here under shall be in writingand signed by or on behalf of the party giving itunder these Terms in the English language, andgiven tothe other party at the address set forth below and deemed given when delivered in person and  shall be sent by e-mail or mailed by prepaid registered courier, or otherwise delivered by hand.
<br /><br />
For the purposes of this clause, the Parties’ electronic mail addresses and mobile numbers shall be the following
<br />
Welleazy:<br />
Email: hello@welleazy.com<br />
Phone: +91-88840 00687<br />
<br />
You: The email address or mobile number provided by you to us or as updated from time to time by notifying Welleazy.
<br /><br />
<b>Assignment:</b><br /><br />

Welleazy may at its sole discretion assign the rights and obligations under this agreement to another party without notice to the User. User shall not assign services or his/her rights/interest/obligations to any other person/third party without prior written consent of Welleazy.
<br /><br />
<b>Force Majeure</b>
<br /><br />
Welleazy will make every effort to deliver performances on time. However, Welleazy shall be free from any claims and damages in case of any delays or non-performances due to any force majeure event, natural or man-made; including conditions which may restrict or prevent performance includingacts of God or acts of the government authoritieson the specific day of service request like traffic weather, non-availability of phone connections, software or other breakdowns, non-accessibility, conditions of risk or any un-foreseen incidents, etc. if beyond the reasonable control of Welleazy.
<br /><br />
<b>Term and Termination</b><br /><br />

This Agreement will remain in full force and effect while the User is a user of any of the Services in any form or capacity.
<br /><br />
<b>Welleazy reserves the right to terminate/refuse/cancel any account in cases:</b><br />
<ul style="list-style:decimal;">
    <li>
        A User breaches any terms and conditions of this terms of use or privacy policy;
    </li>
    <li>
        Welleazy is unable to verify or authenticate any information provided to Welleazy by a User; or
    </li>
    <li>
        Welleazy believes in its sole discretion that User’s actions may cause legal liability for such User, other Users or for Welleazy or are contrary to the interests of the Service.
    </li>
</ul>
Once temporarily suspended, indefinitely suspended or terminated, the User shall not continue to use the Services under the same account, a different account or re­register under a new account, unless explicitly permitted byWelleazy. On termination of an account due to the reasons mentioned herein, such User shall no longer have access to data, messages, files and other content kept on the Services by such User. The User shall ensure that he/she/it maintains has continuous backup of any User­provided content, data or information on the Service, in order to comply with his/her/its record keeping process and practices. Nothing contained in these Terms of Use shall restrict Welleazy’s use of the data or right to publish information made available by a User in the public domain through the Services or any other platform managed by Welleazy after the termination or expiry or cessation of operation of these Terms in relation to a specific User.
<br /><br />
You acknowledge that Welleazy reserves the right to terminate accounts that are inactive for an extended period of time, provided that Welleazy will use its commercially reasonable efforts to provide You with reasonable notice before terminating an inactive account.
<br /><br />
<b>Questions? Concerns? Suggestions</b><br /><br />

Please contact us at hello@welleazy.com to report any violations of these Terms of Service or to pose any questions regarding this Terms of Service or the Services.
<br /><br />
<b>Dispute Resolution By Binding Arbitration:</b><br /><br />

Most user concerns can be resolved quickly and to the User’s satisfaction by emailing Welleazy support at hello@welleazy.com. In the unlikely event that our User support team is unable to resolve a complaint You may have (or if Welleazy has not been able to resolve a dispute it has with You after attempting to do so informally), we each agree to resolve those disputes through arbitration and in accordance with the Arbitration and Conciliation Act, 1996. The arbitration tribunal shall be composed of a sole arbitrator to be appointed in consensus by the Parties. The place of arbitration shall be at Bangalore. The arbitration procedure shall be conducted in the English language and any award or awards shall be rendered in English. The award of the arbitrator shall be final and conclusive and binding upon the Parties.
                    </span>
                </div>
                <br />
            <h3 style="color:#0869b1;"><b>Account Registration</b></h3>
                <div style="border-radius:15px; border:2px solid #bbbaba; overflow-y:auto; height:600px;">
                    <span style="padding: 20px; font-size: medium; color: #2f2e2e;">
                        <b>Your Registration Obligations:</b><br /><br />

You may be required to register with Welleazy in order to access and use certain features of the Services. If You choose to register for the Services, You agree to provide and maintain true, accurate, current and updated complete information about yourself as prompted by Welleazy.
                        <br /><br />
<b>Member Account, Password and Security:</b><br /><br />

You are responsible for maintaining the confidentiality of Your password and account at all times, if any, and are fully responsible for any and all activities that occur under Your password or account. You agree to (a) immediately notify Welleazy of any unauthorized use of Your password or account or any other breach of security, and (b) ensure that You sign out from Your account at the end of each session when accessing the Services. Welleazy shall not be liable for any loss or damage arising from Your failure to comply with this Section.
<br /><br />
<b>Modifications to Services:</b><br /><br />

Welleazy reserves the right to withdraw, modify, suspend or discontinue any functionality or feature of its Website or App or the Services (or any part thereof) at any time without any prior notice.You agree that Welleazy will not be liable to Youor to any third party for any modification, suspension or discontinuance of the Services and You agree to the same without question or demur.<br />
The Welleazy Website or App may contain certain statements that do not constitute promises or assertive statements in all contexts. It is in Your discretion to make use of the information or statements provided. Welleazy makes no representation that all information is accurate, latest or comprehensive. Welleazy is not responsible for inaccuracies/incompleteness of information represented by it or flow not appearing due to faults in certain softwares, applications or devices You may be using.
                        <br /><br />
Data for services available on free of charge on a trial basis may be lost at the end of the trial period and additional terms and conditions may appear or become applicable. You agree that in the event of any problem in using Welleazy Website or App, Your sole remedy shall be to cease using Welleazy Website or App /services.
<br /><br />
All contents of this Website are the property of Welleazy. We grant Youthe permission to download, store, print, display and use the content only for Your personal use and not for any commercial use. You agree not to reproduce any content without the written consent of Welleazy.
<br /><br />
Any suggestions/comments/queries received through Youshall become the property of Welleazy without any obligation and You shall not be entitled to any claim or compensation under any circumstances.
<br /><br />
You grant Welleazy the right to assign this contract to its affiliate or in connection with a merger, acquisition or sale with an intimation on the Website or to You.
<br /><br />
Incase any of the terms and conditions of this agreement become inoperative or invalid or unenforceable, the remaining terms of this agreement shall remaining terms shall remain to be effective and valid. Failure of Welleazy to insist on performance of any one of the terms of this agreement will not mean a waiver of the same term again or any waiver of any other term or condition.
<br /><br />
These terms and conditions will be construed according to Indian laws. Any disputes arising out of these terms and conditions shall be subject to the jurisdiction to the courts of Bangalore, India.
<br /><br />
<b>Use of Third Party Services:</b><br /><br />

As part of the services offered, Youwill also be using the services of one or more third parties with whom Welleazy has tie-ups for services. Welleazy acts as a facilitator in such cases and shall not have any direct control over the third party services. Your use of these third party services will be additionally subject to the separate policies and terms of use of these third parties. Welleazy accepts no liabilities to the terms and conditions of linked websites.
<br /><br />
On using services of Welleazy vendor partners i.e. third parties,Youconsent and agree to share Your personal contact details viz. email id and phone number with such partner vendors who may contact You for registration and/ or associated service.
<br /><br />
<b>Updates:</b><br /><br />

Welleazy in an effort to provide the best services, may make changes to the software platforms or update the software automatically without notice to You. Enhanced updates and portal or web or app based services may be made available on payment of additional charges at the option of Welleazy. Welleazy reserves the right to employ artificial intelligence to respond to queries, or to handle portions of the user interface.
<br /><br />
<b>Changes to User Interface and Terms of Agreement:</b><br /><br />

Welleazy may make any changes to the software or modify its terms and conditions without any notice to You. You are required to read the latest version of the terms and conditions notwithstanding the one-time agreement to the terms and conditions. It shall be presumed that User has read all modified terms and conditions before the availing of services.
<br /><br />
<b>Feedbacks:</b><br /><br />

Welleazy may obtain feedback on services and utilize the same for service improvements. Welleazy reserves the right to have backend scrutiny of feedbacks received and to publish certain or all feedbacks received on social media sites for the purposes of rating analysis or promotion. By agreeing to the terms and conditions, You give Welleazy the right of Your consent for the same. The decision of Welleazy not to consider a feedback in its analysis and/or the labelling of objectionable content in feedback shall be a matter solely at the discretion of Welleazy.
<br /><br />
<b>Assignment:</b><br /><br />

Welleazymay at its sole discretion assign the rights and obligations under this agreement to another party without notice to the User. User shall not assign services or his/her rights/interest/obligations to any other person/third party without prior written consent of Welleazy.
<br /><br />
<b>Indemnity:</b><br /><br />

User shall indemnify and hold harmless Welleazy its affiliates, their directors, agents and employees, from any losses, damages, expenses, including claim or demand, or actions including reasonable attorney’s fees, made by any third party or penalty imposed due to or arising out of breach of these Terms of Use and expressly waives any claim on Welleazy for any costs, damages, liabilities or other consequences for any commissions or omissions by Welleazy or its partners that may result in any inconvenience, harm, financial loss, injury or damage due to promises and performances made by Welleazy in good faith, but not executed for any restricting constraints on Welleazyfor any reason whatsoever, or not executed to the satisfaction of the User. This clause shall apply in protection to Welleazy of any liabilities to the maximum extent permitted by law.
<br /><br />
<b>Confidentiality:</b><br /><br />

You acknowledge that pursuant to this Terms and Conditions, You will have access to confidential information of Welleazy and its affiliates which has been provided by Welleazy. You undertake to keep confidential all data and other confidential information of Welleazy and shall not sell or otherwise make that information available to any third parties.
<br /><br />
<b>Export Control and other restrictions:</b><br /><br />

Welleazy retains the right to terminate the services if User is found to be under any export control restrictions including those of international bodies.Welleazy retains the right to refuse a service and/ or terminate the service prematurely without any financial implication to Welleazy if the User misrepresents information, misuses the services, engages in any unlawful activities or indulges in any anti-social behaviour. Welleazy retains the right to refuse a service or terminate the same prematurely for reasons mentioned above without informing any reason whatsoever.
<br /><br />
<b>Opt – In Benefits by Your Employer:</b><br /><br />

Welleazy Services may be offered as an opt-in benefit by Your Employer. It is Your personal choice whether to take up any of the programs provided and You do so at Your own risk. The services are provided by Welleazy as a service provider and not Your employer and are subject to the Welleazy’s terms of service and privacy policy, which You should review carefully. Your Employer is not responsible or accountable for any liabilities arising out of the advice, diagnosis or assessment of medical condition/ treatment by the external consultant or medical practitioner referred by such external consultant or any other services provided by Welleazy.
<br /><br />
<b>Privacy Tems:</b><br /><br />

Welleazy stores and processes Your personal Information necessary for us to render and complete any services undertaken by You with Welleazy, including any sensitive financial information, transaction data, technical and location data, profile data, marketing and communication data, in accordance with the Information Technology Act, 2000 and the Rules made there under as well as the Privacy Policy of Welleazy from time to time.
<br /><br />
Personal data for registration, storage, including storage of medical records, reports, references, preferences may be part of the User on-boarding, background verification and usage. Welleazy shall use this data for the purpose of making the platform and service and improvements available to You, or for permitted marketing and promotion, or for any mandatory disclosures to government agencies and regulatory bodies. Welleazy assures privacy of Your personal information. Welleazy may however use Your personal information to communicate to You via various media like telephone calling, emails, SMS, WhatsApp messages, newsletters,etc. for the purposes of updating You about the Services or for information about any other products and services it offers or for analytics purposes. By agreeing to these terms and conditions, You specifically give Your free consent to Welleazy to approach You via any of the various media mentioned herein for any of its campaigns or communications. Welleazy is liable to keep Your personal data and medical records for the minimum periods required under law and for the time period required for rendering the services.However, access to Your personal data post the minimum period required under law may not be available to you. Any mistakes in Your data may be informed to Welleazy and Welleazy reserves the right to make necessary corrections, restrict further processing or erase incorrect data within reasonable timelines. For detailed terms of privacy, You may refer the Privacy Policy available on the Website.
                    </span>
                    </div><br />
                <h3 style="color:#0869b1;"><b>Privacy Policy</b></h3>
                <div style="border-radius:15px; border:2px solid #bbbaba; overflow-y:auto; height:600px;">
                    <span style="padding: 20px; font-size: medium; color: #2f2e2e;">
                        It is stated that any information that You provide to Welleazy is subject to our Privacy Policy which governs our collection and use of Your information. You understand and agree that through the use of the Services You consent to the collection and use (as set forth in the Privacy Policy) of this information, processing and use by Welleazy.
                        <br /><br />
Welleazy respects Your right to privacy. Welleazy understands that Your personal data is entrusted to us and values the importance of protecting and respecting Your privacy.
<br /><br />
This Privacy Policy sets out the basis on which we collect and process personal data about You including our practices regarding the collection, use, storage and disclosure of personal data that we collect from You and/or hold about You, and Your rights in relation to that data.
<br /><br />
We collect and process the personal information necessary for us to render and complete any services undertaken by You with Us.We will only ask for Your consent for processing personal information  if there are no other legal grounds to process. In these circumstances, we will always aim to be clear and transparent about why we need Your consent and what we are asking it for.
<br /><br />
At any subsequent stage, You may contact us at +91-88840 00687, and ask to be furnished with the ‘Sensitive Personal Data’ that is held by us, pertaining to YourUser profile and the same will be furnished to you, within a period of ___ from the date of request.
<br /><br />
<b>Opt-Out of further usage of Personal Information:</b><br /><br />

In the limited circumstances where You may have provided Your consent to the collection, processing and transfer of Your personal information for a specific purpose and if You want to remove Your personal data that we have collected about You please e-mail Your request to hello@welleazy.com. To withdraw Your consent, please contact the Us at +91-88840 00687, once we have received notification that You have withdrawn Your consent, and we will no longer process Your information for the purpose or purposes You originally agreed to, unless we have another legitimate basis for doing so in law. Please be aware that there are likely to be implications on our ability to continue our working relationship in the event that we are not able to process Your personal information.
<br />
Please read the following carefully to understand how we process Your personal data. By providing Your personal data to us or by using our services, website or other online or digital platform(s) You are agreeing and consenting to the practices as described or referred to in this Privacy Policy.
<br />
When we refer to ‘we’, ‘us’,‘our’ and ‘Welleazy’, it shall mean Welleazy Healthtech Solutions Private Limited.
<br />
You may address any discrepancies and grievances pertaining to the information provided by You or with respect to processing of information provided by You at +91-88840 00687.
<br /><br />
<b>Collection of personal data</b><br /><br />

When we refer to personal data in this policy, we mean information that can or has the potential to identify You as an individual.
<br /><br />
Accordingly, we may hold and use personal data about You as a customer, a patient or in any other capacity, for example, when You visit one of our websites, complete a form, access our services or speak to us.
<br /><br />
The information we collect from You may include the following:
<br /><br />
<ul style="list-style:disc;">
    <li>
        <b>Identity Data</b> includes first name, maiden name, last name, username or similar identifier, date of birth, the language You use, and gender. This includes information that You give us when You enquire or become a customer or patient of us or apply for a job with us including name, address, contact details (including email address and phone number)
    </li>
    <li>
        <b>Contact Data</b> includes the name and contact details (including phone number and email ids) of You and Your next of kin
    </li>
    <li>
        details of referrals, quotes and other contact and correspondence we may have had with you
    </li>
    <li>
        details of services and/or treatment You have received from us or which have been received from a third party and referred on to us
    </li>
    <li>
        information obtained from customer surveys, promotions and competitions that You have entered or taken part in
    </li>
    <li>
        recordings of calls we receive or make
    </li>
    <li>
        notes and reports about Your health and any treatment and care You have received and/or need, including about clinic and hospital visits and medicines administered, preferences, feedback and survey responses
    </li>
    <li>
        patient feedback and treatment outcome information You provide
    </li>
    <li>
        information about complaints and incidents
    </li>
    <li>
        Financial Data: This includes information You give us when You make a payment to us, such as financial or credit card information
    </li>
    <li>
        other information received from other sources, including from Your use of websites and other digital platforms we operate or the other services we provide, information from business partners, advertising networks, analytics providers, or information provided by other companies who have obtained Your permission to share information about you.
    </li>
</ul>
<br />
Where You have named someone as Your next of kin and provided us with personal data about that individual, it is Your responsibility to ensure that that individual is aware of and accepts the terms of this Privacy Policy.
<br /><br />
Where You use any of our websites, we may automatically collect personal data about You including:
<br /><br />
<ul style="list-style:disc;">
    <li>
        Technical& Location Data:, including the Internet protocol (IP) address used to connect Your computer to the Internet, browser type and version, time zone setting, browser plug-in types and versions, operating system and platform.
    </li>
    <li>
        Information about Your visit, including the full Uniform Resource Locators (URL), clickstream to, through and from our site (including date and time), products You viewed or searched for, page response times, download errors, length of visits to certain pages, page interaction information (such as scrolling, clicks, and mouse-overs), methods used to browse away from the page and other usage data which includes information about how You use the Website/App.
The data that we request from You may include special category data. This includes information that relates to the following:
    </li>
    <li>
        racial or ethnic origin, or
    </li>
    <li>
        genetic data, biometric data for the purpose of uniquely identifying a natural person, or
    </li>
    <li>
        medical records and history, health data including but not limited to physical, physiological and mental health conditions,
    </li>
    <li>
        or data concerning a natural person’s sex life or sexual orientation.
    </li>
</ul>
<b>When do we collect personal data about you?</b><br /><br />

We collect Your personal data You  when you:<br /><br />
<ul style="list-style:disc;">
    <li>
        Register or create an account on our Website/App or avail our services
    </li>
    <li>
        Use or view the Website via Your browser’s cookies.
    </li>
    <li>
        book appointments on our Website
    </li>
    <li>
        enquire about any of our services or treatments
    </li>
    <li>
        register to be a customer or patient with us or book to receive any of our services or treatments
    </li>
    <li>
        fill in a form or survey for us
    </li>
    <li>
        subscribe to our publications, newsletters
    </li>
    <li>
        carry out a transaction on our Website
    </li>
    <li>
        participate in a competition or promotion or other marketing activity
    </li>
    <li>
        make online payments
    </li>
    <li>
        contact us, for example by email, telephone or social media
    </li>
    <li>
        participate in interactive features on any of our Websites.
    </li>
</ul>
<br />
In the interests of training and continually improving our services, calls to Welleazy and its agents may be monitored or recorded. Private calls to and from patients in our clinics are not recorded.
<br /><br />
<b>What personal data we may receive from third parties and other sources?</b><br /><br />

We may collect personal data about You from third parties such as:
<br /><br />
 <ul style="list-style:disc;">
     <li>
         If You are an employee of one of our corporate clients who has taken up one of our services, we may be passed Your name, contact number and email address, in order to get in touch with You to arrange an appointment or collect further information from you;
     </li>
     <li>
         We have a number of independent third parties acting on our behalf who may collect personal data from You to allow us to carry out the services we offer e.g. an independent physician may carry out Your initial Triage call or a subsequent consultation and collect personal data from You which is subsequently shared with Welleazy for the continuity of Your care and may be used for quality and monitoring purposes;
     </li>
     <li>
         We carry out work with panel of specialist for the continuity of Your care we may be passed medical information usually in the form of a referral for the purposes of Your treatment with Welleazy or a third party consultant;
     </li>
     <li>
         Welleazy use the services of independent consultants who carry out procedures at our Clinics. Consultants may need to share Your personal data and medical records with Welleazy.
     </li>
     <li>
         Insurance providers will pass Welleazy personal data of patients who have commenced a claim and require medical treatment with Welleazy. This will normally be in the form of a referral and may consist of basic details e.g full name, date of birth, address, contact number and email address and the type of procedure/treatment they require.
     </li>
   
 </ul> 
<br />
Welleazy reserves the right to update this privacy policy at any time. Updates to our privacy policy will be sent to the email address available with us.
<br /><br />
<b>Amendment to Your data</b><br /><br />

You are responsible for maintaining the accuracy of the information You submit to us, such as Your contact information provided as part of account registration. If Your personal information changes, You may correct, delete inaccuracies, or amend information by making the change on our member information page or by contacting us through +91-88840 00687. We will make good faith efforts to make requested changes in our then active databases as soon as reasonably practicable. If You provide any information that is untrue, inaccurate, out of date or incomplete (or becomes untrue, inaccurate, out of date or incomplete), or Welleazy has reasonable grounds to suspect that the information provided by You is untrue, inaccurate, out of date or incomplete, Welleazy may, at its sole discretion, discontinue the provision of the Services to you. There may be circumstances where Welleazy will not correct, delete or update Your personal data, including (a) where the personal data is opinion data that is kept solely for evaluative purpose; and (b) the personal data is in documents related to a prosecution if all proceedings relating to the prosecution have not been completed.
<br /><br />
<b>How do we lawfully process Your personal data?</b><br /><br />

Your personal data will be kept confidential and secure and will only be used for the purpose(s) for which it was collected and in accordance with this Privacy Policy, applicable Data Protection Laws, clinical records retention periods and clinical confidentiality guidelines.
<br /><br />
<b>We normally process personal data if it is</b><br /><br />
<ul style="list-style:disc;">
    <li>
        necessary to provide You with our services – to enable us to carry out our obligations to You arising from any contract entered into between us and You including relating to the provision by us of services or treatments to You and related matter such as billing, accounting and audit, credit or other payment card verification and anti-fraud screening
    </li>
    <li>
        in our or a third party’s legitimate interests to do so
    </li>
    <li>
        required or allowed by any applicable law
    </li>
    <li>
        with Your explicit consent for example direct marketing communications
    </li>
</ul>
<br />
<b>To process special category data we rely on additional legal grounds and generally, they are as follows</b><br /><br />
<ul style="list-style:disc;">
<li>
    It is necessary for the purposes of preventive or occupational medicine, To assess, medical diagnosis, to provide health or social care treatment, or to manage health or social care systems and services. This may also include monitoring whether the quality of our services or treatment is meeting expectations.
</li>
    <li>
        It is necessary to establish, make or defend legal claims or court action
</li>
    <li>
        It is necessary so that we can comply with employment law
</li>
    <li>
        It is necessary for a public interest purpose in line with any laws that are applicable. This should assist in protecting the public against dishonesty, malpractice or other seriously improper behaviour for example, investigating complaints, clinical concerns, regulatory breaches.
</li>
</ul>
                        <br />
<b>Processing of personal data generally:</b><br /><br />

As stated above, one of the legal grounds for processing data is where it is in our legitimate interests to do so, taking into accountYour interest’s rights and freedom. This allows us to manage the relationship that exists between You and us and can include the following reasons:
<br /><br />
<ul style="list-style:disc;">
    <li>
        provide You with information, products or services that You request from us
    </li>
    <li>
        managing all aspects of our relationship with you, our products and services and any third parties who may provide products or services on our behalf
    </li>
    <li>
        allow You to participate in interactive features of our services, when You choose to do so
    </li>
    <li>
        notify You about changes to our products or services
    </li>
    <li>
        keep our records up to date
    </li>
    <li>
        respond to requests where we have a legal or regulatory obligation to do so
    </li>
    <li>
        check the accuracy of information about You and the quality of Your treatment or care, including auditing medical and billing information for insurance claims as well as part of any claims or litigation process
    </li>
    <li>
        support Your doctor, nurse or other healthcare professional
    </li>
    <li>
        assess the quality and/or type of care You have received (including giving You the opportunity to complete customer satisfaction surveys) and any concerns or complaints You may raise, so that these can be properly investigated
    </li>
    <li>
        to conduct and analyse market research
    </li>
    <li>
        to ensure that content from any of our websites is presented in the most effective manner for You and for Your computer
    </li>
    <li>
        to allow us to enforce our website terms of use, our policy terms and conditions or other contracts, or to protect our or other’s rights, property or safety
    </li>
    <li>
        to share Your personal information with people or organisations in order to run our business or comply with any legal and/or regulatory obligations including to defend ourselves from claims, exercise our rights and adhere to laws and regulations that apply to us and the third parties we work with
    </li>
    <li>
        to take part in, or be the subject of, any sale, purchase, merger or takeover of all or part our business.
    </li>
</ul>
<br />
<b>Exceptions:</b><br /><br />

Our obligations to keep Your personal data shall not apply to any information which:
<br /><br />
<ul style="list-style:disc;">
    <li>
        is at the time of disclosure already in public domain or becomes available to the public through no breach on our part; or
    </li>
    <li>
        is received by us from a third party free to lawfully disclose such information belonging to you; or
    </li>
    <li>
        was in our lawful possession prior to receipt from us as evidenced by written documentation; or
    </li>
    <li>
        is approved for release by written agreement obtained from you; or
    </li>
    <li>
        is required to be disclosed to comply with legal mandatory regulations, a judicial or official order or decree
    </li>
</ul>
<br />
<b>The security of Your personal data</b><br /><br />

We protect all personal data we hold about You by ensuring that we have appropriate organisational and technical security measures in place to prevent unauthorised access or unlawful processing of personal data and to prevent personal data being lost, destroyed or damaged. We conduct assessments to ensure the ongoing security of our information systems.
<br /><br />
Any personal data You provide will be held for as long as is necessary having regard to the purpose for which it was collected and in accordance with all applicable Indian laws.
<br /><br />
Personal data that we collect from You may be transferred to, and stored atservers and machines/clouds leased or rented or purchased byWelleazy. It may also be processed bythird-party service provider for processing the data and shall use globally accepted standards for ensuring and maintaining the protection, security, confidentiality and privacy of all data on its server.
<br /><br />
Where we transfer Your personal data outside India we will ensure that there are adequate protections in place for Your rights, in accordance with Data Protection Laws. By submitting Your personal data, and in providing any personal data to us, You understand the basis for this transfer, storing or processing. We will take all steps reasonably necessary to ensure that Your information is treated securely and in accordance with this Privacy Policy.
<br /><br />
All information You provide to us is stored securely. Any payment transactions on our Website will be processed securely by third party payment processors. Where we have given You (or where You have chosen) a password that enables You to access certain parts of our Website, You are responsible for keeping that password confidential. We ask You not to share a password with anyone.
<br /><br />
The transmission of information via the internet cannot be guaranteed as completely secure. However, we ensure that any information transferred to our Websites is via an encrypted connection. Once we have received Your information, we will use strict procedures and security features to minimise the risk of unauthorised access.
<br /><br />
At Your request, we may transfer personal information to You via email, or You may choose to transfer information to us via email. Email is not a secure method of information transmission; if You choose to send or receive such information via email, You do so understanding the risks associated with doing so.
<br /><br />
<b>Retention of Your personal data:</b><br /><br />

Unless we explain otherwise to you, we will retain Your personal data on the basis of the following guidelines:
<br /><br />
<ul style="list-style:disc;">
    <li>
        for as long as we have a reasonable business need, such as managing our relationship with You and managing our business
    </li>
    <li>
        for as long as we provide services and/or treatment to You and then for as long as someone could bring a claim against us and/or
    </li>
    <li>
        in line with legal and regulatory requirements or guidance.
    </li>
</ul>
                        <br />

<b>Disclosure of Your personal data to third parties</b><br /><br />

In the usual course of our business we may disclose Your personal data (which will be limited to the extent reasonably necessary) to certain third party organisations that we use to support the delivery of our services. This may include the following:
<br /><br />
<ul style="list-style:disc;">
    <li>
        business partners, suppliers and sub-contractors for the performance of any contract we enter into with you,
    </li>
    <li>
        organisations providing IT systems support and hosting in relation to the IT systems on which Your information is stored,
    </li>
    <li>
        third party debt collectors for the purposes of debt collection,
    </li>
    <li>
        delivery companies for the purposes of transportation,
    </li>
    <li>
        third party service providers for the purposes of storage of information and confidential destruction, third party marketing companies for the purpose of sending marketing emails, subject to obtaining appropriate consent.
    </li>
</ul>
                        <br />

Where a third party data processor is used, we ensure that they operate under contractual restrictions with regard to confidentiality and security, in addition to their obligations under Data Protection Laws.
  <br />  <br />
We may also disclose Your personal data to third parties in the event that we sell or buy any business or assets.
  <br />  <br />
In case of a situation wherein we are obliged to comply with the law or a statutory obligation or a legal process, we would be compelled to provide information about you.
  <br />  <br />
<b>Special Category/Health information collected during provision of treatment or services</b>  <br /><br />

Special category data (including information relating to Your health) will only be disclosed to third parties in accordance with this Privacy Policy. That includes third parties involved with Your treatment or care, or in accordance with Indian laws and guidelines of appropriate professional bodies. Where applicable, it may be disclosed to any person or organisation who may be responsible for meeting Your treatment expenses or their agents. It may also be provided to external service providers and regulatory bodies (unless You object) for the purpose of clinical audit to ensure the highest standards of care and record keeping are maintained.
<br /><br />
Medical professionals working with us: We share clinical information about You with the medical professionals as we think necessary for Your treatment. Medical professionals working with us might be our employees, or they might be independent consultants in private practice. In thecase of independent consultants, the consultant is the data controller of Your personal data, either alone or jointly with us and will be required to maintain their own records in accordance with Data Protection Laws and applicable clinical confidential guidelines and retention periods. Where that is the case, we may refer You to that consultant to exercise Your rights over Your data. Our contracts with consultants require them to cooperate with those requests. In all circumstances, those individual consultants will only process Your personal data for the purposes set out in this Privacy Policy or as otherwise notified to you.
<br /><br />
External practitioners: If we refer You externally for treatment, we will share with the person or organisation that we refer You to, the clinical and administrative information we consider necessary for that referral. It will always be clear when we do this.
<br /><br />
Your General Practitioner: If the practitioners treating You believe it to be clinically advisable, we may also share information about Your treatment with Your General Practitioner. You can ask us not to do this, in which case we will respect that request if we are legally permitted to do so, but You should be aware that it can be potentially very dangerous and/or detrimental to Your health to deny Your GP full information about Your medical history, and we strongly advise against it.
<br /><br />
Your insurer: We share with Your medical insurer information about Your treatment, its clinical necessity and its cost, only if they are paying for all or part of Your treatment with us. We provide only the information to which they are entitled. If You raise a complaint or a claim we may be required to share personal data with Your medical insurer for the purposes of investigating any complaint/claim.
<br /><br />
Regulators: We may be requested – and in some cases can be required – to share certain information (including personal data and special category data) about You and Your care with medical regulators, for example if You make a complaint, or the conduct of a medical professional involved in Your treatment is alleged to have fallen below the appropriate standards and the regulator wishes to investigate. We will ensure that we do so within the framework of the law and with due respect for Your privacy.
<br /><br />
From time to time we may also make information available on the basis of necessity for the provision of healthcare, but subject always to patient confidentiality.
<br /><br />
In an emergency and if You are incapacitated, we may also process Your personal data (including special category data) or make personal data available to third parties on the basis of protecting Your ‘vital interest’ (i.e. Your life or Your health).
<br /><br />
We will use Your personal data in order to monitor the outcome of Your treatment by us and any treatment associated with Your care.
<br /><br />
We participate in national audits and initiatives to help ensure that patients are getting the best possible outcomes from their treatment and care. The highest standards of confidentiality will be applied to Your personal data in accordance with Data Protection Laws and confidentiality. Any publishing of this data will be in anonymised, statistical form. Anonymous or aggregated data may be used by us, or disclosed to others, for research or statistical purposes.
<br /><br />
<b>What do we do with any non-personal information collected when accessing the Website?</b><br /><br />

Certain non-personal information which You submit may also be collected to enable us to better understand our customers, to improve our Website, to inform general marketing and to help provide a better experience of our services. We may use cookies to do this. We may also use other companies to set cookies on our Websites and gather cookie information for us – please refer to the information detailed below. From time to time we may also analyse Internet Protocol (IP) addresses or other anonymous data sources.
<br /><br />
<b>Cookies</b><br /><br />

Our Websites use cookies to distinguish You from other users of our Websites. This helps us to provide You with a good experience when You browse our Websites and also allows us to improve our Websites.
<br /><br />
By law, website operators are required to ask for a website User’s permission when placing certain kinds of cookie on their devices for the first time. Where consent is required, the law states that it should be “informed consent”, which means we must ensure that You understand what cookies are and why we want to use them. We are committed to providing the best digital service to You whilst at the same time fully protecting Your privacy. For further information on our cookies policy and how we use cookies through use of all our online services, please see below.
<br /><br />
<b>What are Cookies?</b><br /><br />
Cookies are text files containing small amounts of information which are downloaded to Your device when You visit a website. Cookies are then sent back to the originating website on each subsequent visit, or to another website that recognises that cookie. Cookies are useful because they allow a website to recognise a User’s device.
<br /><br />
Cookies do lots of different jobs, like letting You navigate between pages efficiently, remembering Your preferences, and generally improving YourUser experience. They can also help to ensure that adverts You see online are more relevant to You and Your interests.
<br /><br />
These cookies can be categorized as follows:<br />
<b>1. Strictly Necessary Cookies</b><br /><br />
These cookies are essential in order to enable You to move around our websites and use its features, such as accessing secure areas of the websites. Without these cookies, services You have asked for cannot be provided.
<br /><br />
Your consent is not required for the delivery of those cookies which are strictly necessary to provide services requested by you. We use these types of cookies.
<br /><br />
<b>2.Performance Cookies</b><br /><br />
These cookies collect information about how visitors use a website, for instance which pages visitors go to most often, and if they get error messages from web pages and will allow us to count visits and traffic sources. These cookies don’t collect information that identifies a visitor. All the information these cookies collect is aggregated and therefore anonymous. It is only used to improve how a website works.
<br /><br />
Web analytics that use cookies to gather data to enhance the performance of a website fall into this category. For example, they may be used for testing designs and ensuring a consistent look and feel is maintained for the User. This category does not include cookies used for behavioral/ targeted advertising networks.
<br /><br />
We use these types of cookies. By using our Website and online services You agree that we can place these types of cookies on Your device.
<br /><br />
<b>3.Functionality Cookies</b><br /><br />
These cookies allow our Websites to remember choices You make (such as Your user name, language, or the region You are in) and provide enhanced, more personal features. These cookies can also be used to remember changes You have made to text size, fonts and other parts of web pages that You can customise. They may also be used to provide services You have asked for such as watching a video. The information these cookies collect is generally anonymised and they cannot track Your browsing activity on other websites.
<br /><br />
We use these types of cookies. By using our Websites these You agree that we can place these types of cookies on Your device.
<br /><br />
<b>4.Targeting Cookies/Advertising Cookies</b><br /><br />
These cookies record Your visit to our Website, the pages You have visited and the links You have followed. We will use this information to make our Website and our advertisements on other Websites more relevant to Your interests. We may also share this information with third parties for this purpose. These cookies are used to deliver advertisements more relevant to You and Your interests They are also used to limit the number of times You see an advertisement as well as help measure the effectiveness of the advertising campaign. They are usually placed by advertising networks with the website operator’s permission. They remember that You have visited a website and this information is shared with other organisations such as advertisers. Quite often targeting or advertising cookies will be linked to site functionality provided by the other organisation. We do not use these cookies on our Website.
<br /><br />
Other than the types of cookies listed above, there are necessary cookies required for the website to function and cannot be switched off in our systems. They are usually only set in response to actions made by You which amount to a request for services, such as setting Your privacy preferences, logging in or filling in forms.
<br /><br />
You can set Your browser to block or alert You about these cookies, but some parts of the site will not then work. These cookies do not store any personally identifiable information.
<br /><br />
Please note that third parties (including, for example, advertising networks and providers of external services like web traffic analysis services) may also use cookies, over which we have no control.
<br /><br />
For more information on our position on the use of cookies, please contact us: +91-88840 00687
<br /><br />
<b>How to control Cookies?</b><br /><br />
<ul style="list-style:disc;">
    <li>
        When You first access to the Site we may warn You about the cookies and similar technologies are in use.  By clicking “Accept”, closing the message or continuing to browse the Sites, Youindicate that You understand and agree to use of these technologies as described in this Cookies policy.
    </li>
    <li>
        If You don’t have to accept cookies, consent can be withdrawn at any time, although You may not use certain features on our Website
    </li>
</ul>
                    </span>
                    </div>
                <br />

                <h3 style="color:#0869b1;"><b>Responsible Disclosure Policy</b></h3>
                <div style="border-radius:15px; border:2px solid #bbbaba; overflow-y:auto; height:600px;">
                    <span style="padding: 20px; font-size: medium; color: #2f2e2e;">
                        Welleazy is committed to the safety and security of its systems and services and to the integrity of our data. We recognize the valuable role of the security research community and we encourage responsible reporting of any potential vulnerabilities that may be found in our Site/App/systems and of confidential data from or relating to our services that may be accessible by unauthorized persons. We are committed to working with security researchers to verify and address any potential vulnerabilities that are reported to us in accordance with this Responsible Disclosure Policy and we will not initiate legal action against anyone who makes a report in compliance with this policy.
<br /><br />
<b>Disclosure Policy</b><br /><br />

A security vulnerability is a weakness in the defences of our services that may compromise the safety of our systems. Security researchers and others who become aware of potential vulnerabilities should make a report using the submission instructions below.<br />
We encourage anyone who believes they have discovered a potential vulnerability, or who has become aware of unauthorized access to confidential Welleazy data (including customer data), to inform us immediately to help protect our customers and to improve and strengthen the confidentiality, availability and integrity of our systems.<br />
Welleazy does not offer a bug bounty program or compensation for disclosure.
<br /><br />
<b>Our Commitment to Researchers:</b><br /><br />

If you responsibly report a vulnerability in accordance with this policy, we will:
<br /><br />
<ul style="list-style:disc;">
    <li>
        Promptly investigate all reports. If Your report relates to a potential vulnerability, it should contain details sufficient for us to reproduce the vulnerability.
    </li>
     <li>
         require a reasonable amount of time to remediate the situation before information about the issue is made known to the public.
    </li>
     <li>
         Notify you when the vulnerability has been remediated.
    </li>
</ul>
<br />
<b>User Disclosure Guidelines:</b><br /><br />
<ul style="list-style:disc;">
    <li>
        Do not engage in unauthorized data access, deletion, modification or corruption.
    </li>
    <li>
        Do not cause service disruptions while testing the vulnerability that You discovered.
    </li>
    <li>
        Prohibited research activities include denial of service, spamming, social engineering (including phishing), physical attempts against Welleazy property or data centers, and other activities that may cause damage to Welleazy’s services, systems or to our or our customers’ data, including activities that impact service availability, such as vulnerability scanning tools.
    </li>
</ul>
<br />
<b>Reporting Potential Vulnerabilities</b><br /><br />
<ul style="list-style:disc;">
    <li>
        The information in Your report is extremely sensitive. To make a report to Welleazy Information Security, email to hello@welleazy.com.Reports should include the following information:<br />
        <ul style="list-style:disc;">
            <li>
                Your name and contact information
            </li>
            <li>
                Your organization (if applicable) or LinkedIn/Twitter profile URLs
            </li>
            <li>
                The Welleazy services that may be affected
            </li>
            <li>
                A detailed description of the issue that you’ve discovered
            </li>
            <li>
                Supporting technical details, including descriptions or examples of exploit/attack code, packet captures, and steps to reproduce the issue
            </li>
            <li>
                Any known information about live exploits
            </li>
            <li>
                Your disclosure plans, if any
            </li>
        </ul>
    </li>
</ul>
<br />
                        If Welleazy Information Security Group determines that a reported issue is valid, we will engage in efforts to establish controls, remediate as needed, and, as required by law or as otherwise necessary due to the risk and impact of the matter, inform those who we determine may have been affected by this issue.
                    </span>
                    </div>

            </div>

             </div>
    </form>
</body>
</html>
